#baseURL = "https://neutronimaging-publications.pages.ornl.gov/"
baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "ORNL Neutron Imaging Publications"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = ""
  description = "ORNL Neutron Imaging Publications"
  author = "Jean Bilheux"
  showVisitedLinks = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Neutron Imaging Publications"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "Neutron Imaging Home Page"
url = "https://neutronimaging.pages.ornl.gov"
weight = 2

[[Languages.en.menu.shortcuts]]
name = "HFIR Publications"
url = "https://neutrons.ornl.gov/imaging/publications"
weight = 3

[[Languages.en.menu.shortcuts]]
name = "SNS Publications"
url = "/sns"
weight = 4

[[Languages.fr.menu.shortcuts]]
name = "SNS Publications"
url = "/sns"
weight = 4
