baseurl = "https://neutronimaging-publications.pages.ornl.gov"
languageCode = "en-us"
title = "Neutron Imaging Publications"
theme = "blackburn"
author = "Neutron Imaging Team"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "HFIR and SNS"
  brand = "Publications"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "HFIR"
    pre = "<i class='fa fa-external-link fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "https://neutrons.ornl.gov/imaging/publications"

  [[menu.main]]
    name = "SNS"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "sns"
    url = "/content/sns/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "*"
  facebook = "*"
  instagram = "*"
  github = ""
  stackoverflow = "*"
  linkedin = "*"