baseURL = "https://neutronimaging.pages.ornl.gov"
title = "List of ORNL Neutron Imaging Publications"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "ORNL Neutron Imaging Team"

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = false # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Full list of our imaging publications at the various beam lines of HFIR and SNS"
title404 = "Error!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Neutron Imaging Team"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = false
recentPostsLength = 0
hideSocialMenu = false
showReadingTime = false
noTermCloudShuffle = false
#homepageSections = ["recent_posts"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = ""
facebook = ""
github = ""
instagram = ""
linkedin = ""
twitter = ""
telegram = ""
google_scholar = ""

[params.social.config]
#platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin","telegram","google_scholar"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "HFIR"
weight = 1
identifier = "HFIR"
url = "https://neutrons.ornl.gov/imaging/publications"

[[menu.main]]
name = "Home Page"
weight = 10
identifier = "Imaging Home Page"
url = "https://neutronimaging.pages.ornl.gov"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
